# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-03 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(blank=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
